from datetime import datetime
import json
from typing import Dict, Any, List, Optional
from sqlalchemy.orm import Session

from models.domain import Assessment, AgentEvent, ToolExecution, Evidence, Finding
from schemas.domain import AssessmentReportResponse, FindingResponse


def generate_assessment_report(db: Session, assessment_id: str) -> Optional[AssessmentReportResponse]:
    """
    Assembles a comprehensive, production-quality security assessment report.
    """
    assessment = db.query(Assessment).filter(Assessment.id == assessment_id).first()
    if not assessment:
        return None

    # Retrieve all related entities
    events = (
        db.query(AgentEvent)
        .filter(AgentEvent.assessment_id == assessment_id)
        .order_by(AgentEvent.order.asc())
        .all()
    )
    tools = (
        db.query(ToolExecution)
        .filter(ToolExecution.assessment_id == assessment_id)
        .all()
    )
    findings = (
        db.query(Finding)
        .filter(Finding.assessment_id == assessment_id)
        .all()
    )

    # Calculate severity distribution
    severity_dist = {"High": 0, "Medium": 0, "Low": 0, "Informational": 0}
    for f in findings:
        if f.severity in severity_dist:
            severity_dist[f.severity] += 1
        else:
            severity_dist["Informational"] += 1

    # Formulate timeline
    timeline = [
        {
            "order": e.order,
            "title": e.message,
            "detail": e.detail,
            "kind": e.event_type,
            "timestamp": e.timestamp.isoformat() if e.timestamp else None,
        }
        for e in events
    ]

    # Formulate checks executed
    checks_executed = [
        {
            "tool_name": t.tool_name,
            "status": t.status,
            "duration_ms": t.duration_ms,
            "error": t.error,
        }
        for t in tools
    ]

    # Formulate findings responses
    findings_list = []
    for f in findings:
        snapshot = None
        if f.evidence_snapshot:
            try:
                snapshot = json.loads(f.evidence_snapshot)
            except Exception:
                snapshot = {"raw": f.evidence_snapshot}

        findings_list.append(
            FindingResponse(
                id=f.id,
                assessment_id=f.assessment_id,
                title=f.title,
                category=f.category,
                severity=f.severity,
                confidence=f.confidence,
                description=f.description,
                evidence_reference=f.evidence_reference,
                evidence_snapshot=snapshot,
                why_it_matters=f.why_it_matters,
                remediation=f.remediation,
                verification_status=f.verification_status,
                created_at=f.created_at.isoformat() if f.created_at else None,
            )
        )

    # Formulate remediation recommendations
    remediations = []
    for f in findings:
        if f.remediation and f.severity in ("High", "Medium", "Low"):
            remediations.append({
                "title": f.title,
                "severity": f.severity,
                "remediation": f.remediation,
            })

    # Executive summary synthesis
    total_findings = len(findings)
    high_med = severity_dist["High"] + severity_dist["Medium"]
    if total_findings == 0:
        exec_summary = (
            f"The assessment against {assessment.target} completed successfully under profile '{assessment.profile}'. "
            "No findings were generated by the current passive checks. This does not mean the application has zero "
            "vulnerabilities; it means the HTTP baseline, selected security headers, and cookie attributes inspected "
            "during this run did not produce reportable observations."
        )
    else:
        exec_summary = (
            f"The assessment against {assessment.target} completed with {total_findings} observation(s) identified. "
            f"Found {severity_dist['High']} High, {severity_dist['Medium']} Medium, and {severity_dist['Low']} Low severity items. "
            f"Immediate focus should be placed on addressing the {high_med} actionable configuration item(s) related to defensive headers and cookies."
        )

    return AssessmentReportResponse(
        assessment_id=assessment.id,
        target=assessment.target,
        profile=assessment.profile,
        status=assessment.status,
        created_at=assessment.created_at.isoformat() if assessment.created_at else None,
        completed_at=assessment.completed_at.isoformat() if assessment.completed_at else None,
        executive_summary=exec_summary,
        timeline=timeline,
        checks_executed=checks_executed,
        findings_distribution=severity_dist,
        findings=findings_list,
        remediation_recommendations=remediations,
        agent_evaluation_summary={
            "scope_enforced": True,
            "policy_compliant": True,
            "execution_mode": "LangGraph Orchestrated Agent with Deterministic Tools",
        },
        limitations=[
            "Testing is strictly scoped to passive, non-destructive configuration inspection.",
            "Only HTTP response headers and cookie flags were inspected.",
            "A zero-finding report is not a clean bill of health for the target application.",
            "No active fuzzing, authenticated penetration testing, or invasive payloads were executed.",
            "Results reflect server configuration at the exact moment of tool execution.",
        ],
        disclaimer=(
            "This is an educational security assessment performed against an isolated training environment. "
            "Findings should be independently validated before use in a production security assessment."
        ),
    )
